function (ADD_IDA_PLUGIN target_name )

INCLUDE_DIRECTORIES(${IDASDK_DIR}/include)

ADD_LIBRARY(${target_name} SHARED ${ARGN} )
SET_TARGET_PROPERTIES(${target_name} PROPERTIES PREFIX "" )

IF(NOT ${UNI64})
  ADD_LIBRARY(${target_name}_64 SHARED ${ARGN} )
  SET_TARGET_PROPERTIES(${target_name}_64 PROPERTIES PREFIX "" )
ENDIF()

SET(CMAKE_CXX_STANDARD 17)
SET(OPT_CXX_FLAGS "-std=c++17 -flto -fvisibility=hidden -fvisibility-inlines-hidden")
SET(IDA_COMMON_CXX_FLAGS "-D__X64__ -DUSE_DANGEROUS_FUNCTIONS")

IF (${IDASDK_VER} STREQUAL "83" OR ${IDASDK_VER} STREQUAL "84")
  SET(PRO "_pro")
ELSE ()
  SET(PRO  "")
ENDIF ()

# 自动处理 IDA SDK 9.3.1 移除编译器后缀的变更
macro(set_sdk_lib_path VAR_NAME OS_ARCH BIT)
  set(NEW_PATH "${IDASDK_DIR}/lib/${OS_ARCH}_${BIT}${PRO}")
  if(EXISTS "${NEW_PATH}")
    set(${VAR_NAME} "${NEW_PATH}")
  else()
    # 兼容低版本的带编译器名称的目录
    if("${OS_ARCH}" MATCHES ".*_win")
      set(${VAR_NAME} "${IDASDK_DIR}/lib/${OS_ARCH}_vc_${BIT}${PRO}")
    elseif("${OS_ARCH}" MATCHES ".*_mac")
      set(${VAR_NAME} "${IDASDK_DIR}/lib/${OS_ARCH}_clang_${BIT}${PRO}")
    elseif("${OS_ARCH}" MATCHES ".*_linux")
      set(${VAR_NAME} "${IDASDK_DIR}/lib/${OS_ARCH}_gcc_${BIT}${PRO}")
    endif()
  endif()
endmacro()

IF(MSVC)
  SET(COMMON_FLAGS "${CMAKE_CXX_FLAGS} /std:c++17 -D __NT__ ${IDA_COMMON_CXX_FLAGS} ")
  set_sdk_lib_path(LIB_PATH_64 "x64_win" "64")
  set_sdk_lib_path(LIB_PATH_32 "x64_win" "32")
  IF(${UNI64})
    TARGET_LINK_LIBRARIES(${target_name} ${LIB_PATH_64}/ida.lib)
  ELSE()
    TARGET_LINK_LIBRARIES(${target_name}    ${LIB_PATH_32}/ida.lib)
    TARGET_LINK_LIBRARIES(${target_name}_64 ${LIB_PATH_64}/ida.lib)
  ENDIF()
ELSEIF(APPLE)
  SET(COMMON_FLAGS "${CMAKE_CXX_FLAGS} -D__MAC__ ${IDA_COMMON_CXX_FLAGS}  ${OPT_CXX_FLAGS}")
  IF(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64")
    set_sdk_lib_path(LIB_PATH_64 "arm64_mac" "64")
    set_sdk_lib_path(LIB_PATH_32 "arm64_mac" "32")
  ELSE()
    set_sdk_lib_path(LIB_PATH_64 "x64_mac" "64")
    set_sdk_lib_path(LIB_PATH_32 "x64_mac" "32")
  ENDIF()

  IF(${UNI64})
    TARGET_LINK_LIBRARIES(${target_name}    ${LIB_PATH_64}/libida.dylib -flto)
  ELSE()
    TARGET_LINK_LIBRARIES(${target_name}    ${LIB_PATH_32}/libida.dylib -flto)
    TARGET_LINK_LIBRARIES(${target_name}_64 ${LIB_PATH_64}/libida64.dylib -flto)
  ENDIF()
ELSEIF(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
  SET(COMMON_FLAGS "${CMAKE_CXX_FLAGS} -D__LINUX__ ${IDA_COMMON_CXX_FLAGS} ${OPT_CXX_FLAGS}")
  SET(GCC_LINK_FLAGS "-Wl,--version-script=${IDASDK_DIR}/plugins/exports.def -Wl,--strip-debug,--discard-all,--strip-all,--discard-locals -flto=auto")
  set_sdk_lib_path(LIB_PATH_64 "x64_linux" "64")
  set_sdk_lib_path(LIB_PATH_32 "x64_linux" "32")

  IF(${UNI64})
    TARGET_LINK_LIBRARIES(${target_name}    ${LIB_PATH_64}/libida.so ${OPT_CXX_FLAGS} ${GCC_LINK_FLAGS})
  ELSE()
    TARGET_LINK_LIBRARIES(${target_name}    ${LIB_PATH_32}/libida.so ${OPT_CXX_FLAGS} ${GCC_LINK_FLAGS})
    TARGET_LINK_LIBRARIES(${target_name}_64 ${LIB_PATH_64}/libida64.so ${OPT_CXX_FLAGS} ${GCC_LINK_FLAGS})
  ENDIF()
ENDIF ()

IF(${UNI64})
   SET_TARGET_PROPERTIES(${target_name} PROPERTIES COMPILE_FLAGS "${COMMON_FLAGS} -D__EA64__")
   SET_TARGET_PROPERTIES(${target_name} PROPERTIES OUTPUT_NAME "${target_name}" )
ELSE()
   SET_TARGET_PROPERTIES(${target_name}    PROPERTIES COMPILE_FLAGS  ${COMMON_FLAGS})
   SET_TARGET_PROPERTIES(${target_name}_64 PROPERTIES COMPILE_FLAGS "${COMMON_FLAGS} -D__EA64__")
   SET_TARGET_PROPERTIES(${target_name}    PROPERTIES OUTPUT_NAME "${target_name}" )
   SET_TARGET_PROPERTIES(${target_name}_64 PROPERTIES OUTPUT_NAME "${target_name}64" )
ENDIF()

endfunction()
